name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'PankratzLab',
              repo: 'Genvisis-Website',
              workflow_id: 'deploy.yml',
              ref: 'main'
            })
            console.log(result)
